environment:

  matrix:

    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37-x64

# image:
#   - Visual Studio 2015
#   - Visual Studio 2017
#   - Visual Studio 2019
#   - Ubuntu

install:
  # We need wheel installed to build wheels
  # - "%PYTHON%\\python.exe -m pip install wheel"
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - make install

build: off

test_script:
  - make test

after_test:
  - make clean

# on_success:
#   - make submitcoverage
