environment:

  matrix:

    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37-x64

image:
  - Visual Studio 2019
  - macos-mojave
  - Ubuntu

install:
  # We need wheel installed to build wheels
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - make dev_install

build: off

test_script:
  - make test

after_test:
  - make clean

# on_success:
#   - make submitcoverage
