environment:

  matrix:

    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37-x64

image:
  - Visual Studio 2019
  - macos-mojave
  - Ubuntu

install:
  # We need wheel installed to build wheels
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # - make dev_install

build: off

test_script:
  # - make test

  - make dev_install
  - pip uninstall -y cython
  - make test
  - make clean
  - make dev_install
  - make test
  - make clean

# after_test:
#   - make clean

# on_success:
#   - make submitcoverage
