environment:

  matrix:

    - fast_finish: true
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37-x64

image:
  - Visual Studio 2019
  - macos-mojave
  - Ubuntu

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - make install  # test that package installs as is
  - make clean
  - make cython_install  # dev_install causes some of the tests to be skipped

build: off

test_script:
  - make test

after_test:
  - make clean

# on_success:
#   - make submitcoverage
