environment:

  matrix:

    - PYTHON: C:\Python36-x64
      fast_finish: true
    - PYTHON: C:\Python37-x64
      fast_finish: true

image:
  - Visual Studio 2019
  - macos-mojave
  - Ubuntu

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # - make install # test that package installs as is
  # - make clean
  # - make cython_install # dev_install causes some of the tests to be skipped
  - make dev_install

# build_script:
#   - make dev_install

test_script:
  - make test

after_test:
  - make clean

# on_success:
#   - make submitcoverage
