environment:

  matrix:

    - PYTHON: C:\Python36-x64
      fast_finish: true
    - PYTHON: C:\Python37-x64
      fast_finish: true

image:
  - Visual Studio 2019
  - macos-mojave
  - Ubuntu

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - make cython_install
  # appveyor checks that if we cythonize the pyx file then the tests pass.
  # travis-ci checks that the already cythonized .c file passes.

test_script:
  - make test

after_test:
  - make clean

# on_success:
#   - make submitcoverage
