environment:

  matrix:

    - PYTHON: C:\Python36-x64
      fast_finish: true
    - PYTHON: C:\Python37-x64
      fast_finish: true

image:
  - Visual Studio 2019
  - macos-mojave
  - Ubuntu

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # - make install || exit /b %errorlevel%  # test that package installs as is
  # - make clean || exit /b %errorlevel%
  # - make cython_install || exit /b %errorlevel%  # dev_install causes some of the tests to be skipped
  - make dev_install || exit /b %errorlevel%

build: off

test_script:
  - cmd: make test || exit /b %errorlevel%
  - sh: make test

after_test:
  - make clean

# on_success:
#   - make submitcoverage
