language: python

os:
  - linux
  # - osx
  # - windows

python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
#  - "3.8-dev"

install:
  - make dev_install

script:
  - make test

after_script:
  - make submitcoverage
  - make clean
